### ISSUE TITLE
Meaning of 'source' and 'isKeyCitation'

### ISSUE THREAD

**Issue by jessicalamjh** [allenai/scicite#15]
What do 'source' and 'isKeyCitation' mean in SciCite? I've tried looking in the original paper, in the repo description, and even in the code to find an answer but couldn't find anything on them.

P.S. I'm rather new to actually asking interacting with others on Github. Please let me know if I should ask such questions in private emails next time instead.

**Comment by armancohan** [comment]
You can ignore these fields, they are about our internal data and they are not used in training or evaluation of the model.
The `isKeyCitation` field specifies whether a citation is highly influential as defined by Semantic Scholar. 
Please see here for more information: https://www.semanticscholar.org/faq#influential-citations
