### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by jacklxc** [allenai/scicite#4]
The readme file seems to be outdated. For example, in the training section, there is no such file called `scicite/run_model.py `. Can you update the instructions? Thank you.

**Comment by jacklxc** [comment]
Can you also include the instruction of how to fine-tune the model? As far as I tested, only predict still works as instructed.

**Comment by acohan** [comment]
The training script was added and the readme file was updated accordingly. Thanks for pointing this out!

**Comment by jacklxc** [comment]
Thank you. Is it possible to also include the instruction to fine-tune the trained model?

**Comment by acohan** [comment]
You can download the trained model, decompress the model.tar.gz archive file and set the `--serialization-dir` option to that directory. Then use the `--recover` option.
So basically 
```
python scripts/train_local.py train_multitask_2 [path-to-config-file.json] \
-s [path-to-decompressed-model.tar.gz/] 
--include-package scicite 
--recover
```
