### ISSUE TITLE
how do i create the training dataset ?

### ISSUE THREAD

**Issue by msaraswathy** [allenai/scicite#5]
I want to create my own training dataset can someone please tell me how do i create it on my own is there any automatic script to do the same ? if not please give the steps to create the training dataset myself ?

**Comment by armancohan** [comment]
It should be relatively easy to use the code with your own dataset. You need to create a jsonlines file (a text file where each line is a json object). Each json should have the exact keys as in the provided dataset. The most important ones are `string` and `label`.

**Comment by msaraswathy** [comment]
please explain me which you given sample test jsonlines file where each line how do i create it on my own. how do i get each keys in json object. Is there any script for that.

**Comment by AnakinShieh** [comment]
I have a similar question, I mean, if I want to create my own training data, besides creating the different types of labels, I also have to get the citing string, location, etc from the raw pdf. Is there any easy way we can use to extract it, the citation and the context of citation from raw pdf files?

**Comment by armancohan** [comment]
You can use tools like ScienceParse (https://github.com/allenai/spv2) or Grobid (https://github.com/kermitt2/grobid-client-python) to convert pdf to plaintext and also get citation information.
